name: my first workflow
on: [push]
jobs:
        run-tests:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                          name: Check the repository
                        - run: pip install pytest
                        - runa: pytest
